### ISSUE TITLE
NullReferenceException when StaticPaginator receives reaction on .NET 5.0

### ISSUE THREAD

**Issue by lordDashh** [Playwo/Discord.InteractivityAddon#4]
When a reaction is added to the paginator message, it throws an error and does nothing. The timeout works fine, though.

## Info
.net version: 5.0.100
also tested with: 5.0.100-rc.2.20479.15 (preview)

## Exception
```cs
A ReactionAdded handler has thrown an unhandled exception.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Interactivity.Extensions.Extensions.DeleteAsync(SocketReaction reaction, BaseSocketClient client)
   at Interactivity.Pagination.Paginator.HandleReactionAsync(BaseSocketClient client, SocketReaction reaction)
   at Interactivity.InteractivityService.<>c__DisplayClass24_0.<<SendPaginatorAsync>g__CheckReactionAsync|2>d.MoveNext()
--- End of stack trace from previous location ---
   at Discord.EventExtensions.InvokeAsync[T1,T2,T3](AsyncEvent`1 eventHandler, T1 arg1, T2 arg2, T3 arg3)
   at Discord.WebSocket.DiscordSocketClient.TimeoutWrap(String name, Func`1 action)
```

## Reproduce
```cs
// inter is the InteractivityService
await inter.SendPaginatorAsync(new StaticPaginatorBuilder()
	.WithPages(new PageBuilder().WithText("hi"), new PageBuilder().WithText("bye"))
	.WithUsers(this.Context.User)
	.WithFooter(PaginatorFooter.PageNumber)
	.WithDefaultEmotes()
	.Build(), this.Context.Channel, TimeSpan.FromMinutes(5));
```

**Comment by Playwo** [comment]
Which version of the Addon are you using? 
The problem is that either the user or the message is not in cache.
I suspect it being the user because the timeout works fine. 
There was a change to that in rc3 of the addon so give that a try. (Latest dnet and addon preview work, there are some compatibility problems when mixing older and later version)

Since that change the user does not have to be cached anymore but the message is still required.
Let me know if the error persists in the later versions.

**Comment by lordDashh** [comment]
Alright, so the problem was that I hadn't increased the `MessageCacheSize` config option. I updated to the prerelease version
first and then I got the error:
```cs
A ReactionAdded handler has thrown an unhandled exception.
System.InvalidOperationException: Could not load the paginator message to an emote! Try increasing your Message Cache
   at Interactivity.Extensions.Extensions.DeleteAsync(SocketReaction reaction, BaseSocketClient client)
   at Interactivity.Pagination.Paginator.HandleReactionAsync(BaseSocketClient client, SocketReaction reaction)
   at Interactivity.InteractivityService.<>c__DisplayClass24_0.<<SendPaginatorAsync>g__CheckReactionAsync|2>d.MoveNext()
--- End of stack trace from previous location ---
   at Discord.EventExtensions.InvokeAsync[T1,T2,T3](AsyncEvent`1 eventHandler, T1 arg1, T2 arg2, T3 arg3)
   at Discord.WebSocket.DiscordSocketClient.TimeoutWrap(String name, Func`1 action)
```

After increasing the cache size, everything works well. I've downgraded back to stable and it also works.
