### ISSUE TITLE
NullReferenceException when creating paginator with footer

### ISSUE THREAD

**Issue by Matcheryt** [Playwo/Discord.InteractivityAddon#6]
## Steps to reproduce
If you try to build a paginator with a footer, it will throw a NullReferenceException.

```C#
var paginator = new StaticPaginatorBuilder()
                .WithUsers(context.User)
                .WithFooter(PaginatorFooter.PageNumber)
                .WithEmotes(new Dictionary<IEmote, PaginatorAction>()
                {
                    { new Emoji("⏮️"), PaginatorAction.SkipToStart },
                    { new Emoji("⬅️"), PaginatorAction.Backward },
                    { new Emoji("➡️"), PaginatorAction.Forward },
                    { new Emoji("⏭️"), PaginatorAction.SkipToEnd }
                })
                .WithPages(pages)
                .WithTimoutedEmbed(pages[0].Build().Embed.ToEmbedBuilder())
                .Build();           
```

## Tested on
- .NET 5.0
- Discord.InteractivityAddon version 2.2.0-rc7 (tested rc6 also, it doesn't have this problem)

## Exception

```C#
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Discord.InteractivityAddon
  StackTrace:
   at Interactivity.PageBuilder.WithPaginatorFooter(PaginatorFooter footer, Int32 page, Int32 totalPages, IList`1 users)
   at Interactivity.Pagination.StaticPaginatorBuilder.Build(Int32 startPage)
   at CobraBot.Services.MusicService.<SearchAsync>d__15.MoveNext()
```

**Comment by Playwo** [comment]
Thanks for reporting, I've overlooked that one 👍
